//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Nombre de archivo original:
// Fecha de generación: 14/10/2013 19:31:51
namespace Entity
{
    
    /// <summary>
    /// No hay ningún comentario para MSDNVideoEntities1 en el esquema.
    /// </summary>
    public partial class MSDNVideoEntities1 : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto MSDNVideoEntities1 usando la cadena de conexión encontrada en la sección 'MSDNVideoEntities1' del archivo de configuración de la aplicación.
        /// </summary>
        public MSDNVideoEntities1() : 
                base("name=MSDNVideoEntities1", "MSDNVideoEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto MSDNVideoEntities1.
        /// </summary>
        public MSDNVideoEntities1(string connectionString) : 
                base(connectionString, "MSDNVideoEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto MSDNVideoEntities1.
        /// </summary>
        public MSDNVideoEntities1(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MSDNVideoEntities1")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para Usuarios en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Usuarios> Usuarios
        {
            get
            {
                if ((this._Usuarios == null))
                {
                    this._Usuarios = base.CreateQuery<Usuarios>("[Usuarios]");
                }
                return this._Usuarios;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Usuarios> _Usuarios;
        /// <summary>
        /// No hay ningún comentario para Usuarios en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToUsuarios(Usuarios usuarios)
        {
            base.AddObject("Usuarios", usuarios);
        }
    }
    /// <summary>
    /// No hay ningún comentario para MSDNVideoModel.Usuarios en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// UsuarioID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MSDNVideoModel", Name="Usuarios")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Usuarios : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Usuarios.
        /// </summary>
        /// <param name="usuarioID">Valor inicial de UsuarioID.</param>
        /// <param name="nIF">Valor inicial de NIF.</param>
        /// <param name="rol">Valor inicial de Rol.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Usuarios CreateUsuarios(int usuarioID, string nIF, short rol)
        {
            Usuarios usuarios = new Usuarios();
            usuarios.UsuarioID = usuarioID;
            usuarios.NIF = nIF;
            usuarios.Rol = rol;
            return usuarios;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad UsuarioID en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int UsuarioID
        {
            get
            {
                return this._UsuarioID;
            }
            set
            {
                this.OnUsuarioIDChanging(value);
                this.ReportPropertyChanging("UsuarioID");
                this._UsuarioID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UsuarioID");
                this.OnUsuarioIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _UsuarioID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioIDChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad NIF en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIF
        {
            get
            {
                return this._NIF;
            }
            set
            {
                this.OnNIFChanging(value);
                this.ReportPropertyChanging("NIF");
                this._NIF = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NIF");
                this.OnNIFChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIF;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIFChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIFChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Clave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Clave
        {
            get
            {
                return this._Clave;
            }
            set
            {
                this.OnClaveChanging(value);
                this.ReportPropertyChanging("Clave");
                this._Clave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Clave");
                this.OnClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Clave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnClaveChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Rol en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short Rol
        {
            get
            {
                return this._Rol;
            }
            set
            {
                this.OnRolChanging(value);
                this.ReportPropertyChanging("Rol");
                this._Rol = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Rol");
                this.OnRolChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _Rol;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRolChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRolChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Telefono en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Telefono
        {
            get
            {
                return this._Telefono;
            }
            set
            {
                this.OnTelefonoChanging(value);
                this.ReportPropertyChanging("Telefono");
                this._Telefono = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Telefono");
                this.OnTelefonoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Telefono;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTelefonoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTelefonoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Email en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Email;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEmailChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEmailChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Direccion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Direccion
        {
            get
            {
                return this._Direccion;
            }
            set
            {
                this.OnDireccionChanging(value);
                this.ReportPropertyChanging("Direccion");
                this._Direccion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Direccion");
                this.OnDireccionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Direccion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDireccionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDireccionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Ciudad en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Ciudad
        {
            get
            {
                return this._Ciudad;
            }
            set
            {
                this.OnCiudadChanging(value);
                this.ReportPropertyChanging("Ciudad");
                this._Ciudad = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Ciudad");
                this.OnCiudadChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Ciudad;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCiudadChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCiudadChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Provincia en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Provincia
        {
            get
            {
                return this._Provincia;
            }
            set
            {
                this.OnProvinciaChanging(value);
                this.ReportPropertyChanging("Provincia");
                this._Provincia = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Provincia");
                this.OnProvinciaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Provincia;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProvinciaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProvinciaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad CodigoPostal en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<decimal> CodigoPostal
        {
            get
            {
                return this._CodigoPostal;
            }
            set
            {
                this.OnCodigoPostalChanging(value);
                this.ReportPropertyChanging("CodigoPostal");
                this._CodigoPostal = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CodigoPostal");
                this.OnCodigoPostalChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<decimal> _CodigoPostal;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoPostalChanging(global::System.Nullable<decimal> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoPostalChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Saldo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<decimal> Saldo
        {
            get
            {
                return this._Saldo;
            }
            set
            {
                this.OnSaldoChanging(value);
                this.ReportPropertyChanging("Saldo");
                this._Saldo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Saldo");
                this.OnSaldoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<decimal> _Saldo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSaldoChanging(global::System.Nullable<decimal> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSaldoChanged();
    }
}
