//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 07/10/2013 17:47:27
namespace EjemploEntityFramework
{
    
    /// <summary>
    /// There are no comments for MSDNVideoDBEntities in the schema.
    /// </summary>
    public partial class MSDNVideoDBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MSDNVideoDBEntities object using the connection string found in the 'MSDNVideoDBEntities' section of the application configuration file.
        /// </summary>
        public MSDNVideoDBEntities() : 
                base("name=MSDNVideoDBEntities", "MSDNVideoDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MSDNVideoDBEntities object.
        /// </summary>
        public MSDNVideoDBEntities(string connectionString) : 
                base(connectionString, "MSDNVideoDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MSDNVideoDBEntities object.
        /// </summary>
        public MSDNVideoDBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MSDNVideoDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Actores in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Actores> Actores
        {
            get
            {
                if ((this._Actores == null))
                {
                    this._Actores = base.CreateQuery<Actores>("[Actores]");
                }
                return this._Actores;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Actores> _Actores;
        /// <summary>
        /// There are no comments for Actores in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToActores(Actores actores)
        {
            base.AddObject("Actores", actores);
        }
    }
    /// <summary>
    /// There are no comments for MSDNVideoDBModel.Actores in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ActorID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MSDNVideoDBModel", Name="Actores")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Actores : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Actores object.
        /// </summary>
        /// <param name="actorID">Initial value of ActorID.</param>
        /// <param name="nombre">Initial value of Nombre.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Actores CreateActores(int actorID, string nombre)
        {
            Actores actores = new Actores();
            actores.ActorID = actorID;
            actores.Nombre = nombre;
            return actores;
        }
        /// <summary>
        /// There are no comments for property ActorID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ActorID
        {
            get
            {
                return this._ActorID;
            }
            set
            {
                this.OnActorIDChanging(value);
                this.ReportPropertyChanging("ActorID");
                this._ActorID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ActorID");
                this.OnActorIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ActorID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnActorIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnActorIDChanged();
        /// <summary>
        /// There are no comments for property Nombre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
        /// <summary>
        /// There are no comments for property UrlPersonal in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string UrlPersonal
        {
            get
            {
                return this._UrlPersonal;
            }
            set
            {
                this.OnUrlPersonalChanging(value);
                this.ReportPropertyChanging("UrlPersonal");
                this._UrlPersonal = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UrlPersonal");
                this.OnUrlPersonalChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _UrlPersonal;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUrlPersonalChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUrlPersonalChanged();
    }
}
